# Example configuration for Black.

# NOTE: you have to use single-quoted strings in TOML for regular expressions.
# It's the equivalent of r-strings in Python.  Multiline strings are treated as
# verbose regular expressions by Black.  Use [ ] to denote a significant space
# character.

[tool.black]
line-length = 120
exclude = '''
/(
    \.eggs
  | \.git
  | example
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | \.vscode
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.pytest.ini_options]
filterwarnings = [
    "ignore:PendingDeprecationWarning",
]
# [tool.tox]
# legacy_tox_ini = """
# [tox]
# envlist = py37

# [testenv]
# deps = numpy >= 1.19.0, <1.20
# install_command = pip install --trusted-host pypi.firstrf.com --index-url http://pypi.firstrf.com/simple {opts} {packages} --extra-index-url https://pypi.org/simple
# setenv =
#     PYTHONPATH = {toxinidir}/rftools
#     COVERAGE_FILE = .coverage.{envname}
# commands =
#     pip install -e .
#     pip install -r requirements_dev.txt
#     pytest .
# """
